MOVIE_CONFIG = {
    fps = 60, -- same as setting frame
}

-- TAS FPS Parameter (VERY IMPORTANT FOR TIMINGS)
env.fps=120

-- Initial TAS Setup
print("Setting Playback Speed")
movie.playback_speed(1)

print("Quick Test (1)")
movie.frame_advance(50)

print("Quick Test (2)")
movie.frame_advance()
key.hold("Escape")
movie.frame_advance()
key.release("Escape")

print("Intro Skip Test (1)")
movie.frame_advance()
key.hold("Escape")
movie.frame_advance()
key.release("Escape")

print("Intro Skip Test (2)")
movie.frame_advance(40)

print("Intro Skip Test (3)")
movie.frame_advance(10)

print("Mouse Movement Test (1)")
movie.frame_advance(4)

print("Mouse Movement Test (2)")
mouse.move(500,600)
movie.frame_advance(3)

print("Mouse Movement Test (3)")
movie.frame_advance()
mouse.move(500,600)
mouse.left(true)
movie.frame_advance()
mouse.move(500,600)
mouse.left(false)

print("Mouse Movement Test (4)")
movie.frame_advance()
mouse.move(500,600)
mouse.left(true)
movie.frame_advance()
mouse.move(500,600)
mouse.left(false)

print("Ending Mouse Testing")
movie.frame_advance(10)

-- the start of your code!

print("Selecting HARMLESS Difficulty")
movie.frame_advance(30)
mouse.move(560,840)
movie.frame_advance(30)
mouse.left(true)
movie.frame_advance(30)
mouse.left(false)
movie.frame_advance(30)

print("Selecting ACT I: INFINITE HYPERDEATH")
mouse.move(960,680)
movie.frame_advance(30)
mouse.left(true)
movie.frame_advance(30)
mouse.left(false)
movie.frame_advance(30)

print("Selecting 3-2: IN THE FLESH")
mouse.move(1900,950)
movie.frame_advance(30)
mouse.left(true)
movie.frame_advance(30)
mouse.move(1900,200)
movie.frame_advance(30)
mouse.left(false)
movie.frame_advance(30)
mouse.move(1390,500)
movie.frame_advance(30)
mouse.left(true)
movie.frame_advance(30)
mouse.left(false)
movie.frame_advance(30)

-- IMPORTANT!! you need this in order to make angle adjustments AND to do anything really
print("Setting Up Level Parameters")
mouse.move(960,540)
movie.frame_advance(150)

print("Enabling TAB Menu")
key.hold("tab")
movie.frame_advance(2)
key.release("tab")
movie.frame_advance(2)
key.hold("tab")
movie.frame_advance(2)
key.release("tab")
movie.frame_advance(2)

-- definitely can be simplified, but i'm not planning on doing so atm
print("Enabling Cheats (Just in case...)")
key.hold("uparrow")
movie.frame_advance()
key.release("uparrow")
movie.frame_advance()
key.hold("uparrow")
movie.frame_advance()
key.release("uparrow")
movie.frame_advance()
key.hold("downarrow")
movie.frame_advance()
key.release("downarrow")
movie.frame_advance()
key.hold("downarrow")
movie.frame_advance()
key.release("downarrow")
movie.frame_advance()
key.hold("leftarrow")
movie.frame_advance()
key.release("leftarrow")
movie.frame_advance()
key.hold("rightarrow")
movie.frame_advance()
key.release("rightarrow")
movie.frame_advance()
key.hold("leftarrow")
movie.frame_advance()
key.release("leftarrow")
movie.frame_advance()
key.hold("rightarrow")
movie.frame_advance()
key.release("rightarrow")
movie.frame_advance()
key.hold("b")
movie.frame_advance()
key.release("b")
movie.frame_advance()
key.hold("a")
movie.frame_advance()
key.release("a")
movie.frame_advance()

print("Clicking On Cheats Prompt")
mouse.move(830,430)
movie.frame_advance(20)
mouse.left(true)
movie.frame_advance(20)
mouse.left(false)
movie.frame_advance(20)

print("Clicking On Resume")
mouse.move(960,680)
movie.frame_advance(20)
mouse.left(true)
movie.frame_advance(20)
mouse.left(false)
movie.frame_advance(20)

-- Redline Setup --
key.hold("d")
movie.frame_advance(2)
key.release("d")
key.hold("1")
movie.frame_advance()
key.release("1")
movie.frame_advance()
key.hold("5")
movie.frame_advance()
key.release("5")
movie.frame_advance()
key.hold("5")
movie.frame_advance()
key.release("5")
movie.frame_advance(100)
mouse.right(true)
movie.frame_advance()
mouse.right(false)
movie.frame_advance(50)
mouse.left(true)
movie.frame_advance()
mouse.left(false)
movie.frame_advance()
key.hold("w")
movie.frame_advance(50)
key.release("w")
movie.frame_advance(75)
mouse.left(true)
movie.frame_advance()
mouse.left(false)
key.hold("w")
movie.frame_advance(150)
key.release("w")
movie.frame_advance()
key.hold("s")
movie.frame_advance()
key.hold("shift")
movie.frame_advance()
key.release("shift")
movie.frame_advance(10)
key.hold("shift")
movie.frame_advance()
key.release("shift")
key.release("s")